export interface Product {
  id: number;
  title: string;
  description: string;
  price: number;
  originalPrice?: number;
  category: string;
  image: string;
  images: string[];
  inStock: boolean;
  brand?: string;
  model?: string;
  warranty?: string;
  delivery?: string;
  features?: string[];
  specifications?: { label: string; value: string }[];
}

/**
 * Generate product-specific image paths in subfolders.
 * Each product uses `/images/products/product_<seed>/image<n>.svg`.
 * Place matching image files in `public/images/products/product_<seed>/image1.svg`..`image4.svg`.
 */
function makeProductImages(seed: number): string[] {
  const folder = `/images/products/product_${seed}`;
  return Array.from({ length: 4 }, (_, offset) => `${folder}/image_${offset + 1}.jpg`);
}

export const products: Product[] = [
  {
    id: 1,
    title: "HIKVISION 2MP ColorVu Bullet Camera",
    description: "High-definition surveillance camera with night vision, motion detection, and weatherproof housing.",
    price: 380000,
    originalPrice: 450000,
    category: "cctv",
    image: makeProductImages(1)[0],
    images: makeProductImages(1),
    inStock: true,
    brand: "Hikvision",
    model: "DS-2CE10DF0T-PFS IP67",
    warranty: "12 Months",
    delivery: "Free delivery within Kampala",
    features: [
      "1080p Full HD resolution",
      "Night vision up to 30 meters",
      "IP67 weatherproof rating",
      "Motion detection alerts",
      "Remote viewing via mobile app",
    ],
    specifications: [
      { label: "Resolution", value: "1920x1080" },
      { label: "Lens", value: "3.6mm" },
      { label: "Night Vision Range", value: "30m" },
      { label: "Power Supply", value: "12V DC" },
      { label: "Operating Temperature", value: "-30°C to 60°C" },
    ],
  },
  {
    id: 2,
    title: "HD SOLAR SMART WIFI CAMERA",
    description: "Smart compound wifi camera with remote viewing via mobile app, laptop and HD Screen.",
    price: 850000,
    originalPrice: 950000,
    category: "cctv",
    image: makeProductImages(2)[0],
    images: makeProductImages(2),
    inStock: true,
    brand: "SmarTTech",
    warranty: "12 Months",
    delivery: "Free delivery within Kampala",
  },
  {
    id: 3,
    title: "Fast 8 Channael HikVision NVR",
    description: "Lightning fast video processing NVR with 8 POE channel ports.",
    price: 1200000,
    category: "cctv",
    image: makeProductImages(3)[0],
    images: makeProductImages(3),
    inStock: true,
    brand: "Hikvision",
    warranty: "1 Year",
    delivery: "Free delivery within Kampala",
  },
  {
    id: 14,
    title: "Solar Powered CCTV Kit",
    description: "Off-grid surveillance system with solar panel and 4G connectivity.",
    price: 1500000,
    category: "cctv",
    image: makeProductImages(4)[0],
    images: makeProductImages(4),
    inStock: true,
    brand: "Reolink",
    warranty: "2 years",
    delivery: "Free delivery within Kampala",
  },
  {
    id: 17,
    title: "Hikvison 4MP Bullet Camera",
    description: "High Resolution Bullet camera for outdoor survillence.",
    price: 520000,
    originalPrice: 600000,
    category: "cctv",
    image: makeProductImages(5)[0],
    images: makeProductImages(5),
    inStock: true,
    brand: "Hikvision",
    warranty: "2 years",
    delivery: "Free delivery within Kampala",
  },
  {
    id: 21,
    title: "Fast 16 Channel Hikvision POE NVR",
    description: "16 Lightning Fast Port Hikvison NVR with AI Video Analytics and Easy Tracking.",
    price: 2800000,
    category: "cctv",
    image: makeProductImages(6)[0],
    images: makeProductImages(6),
    inStock: true,
    brand: "Hikvision",
    warranty: "2 years",
    delivery: "Free delivery within Kampala",
  },
  {
    id: 24,
    title: "Black CAT6 UTP Outdoor Ethernet Cable",
    description: "Fast CAT6 UTP outdoor ethernet cable perfect for cctv and local networks setup.",
    price: 45000,
    category: "cctv",
    image: makeProductImages(7)[0],
    images: makeProductImages(7),
    inStock: true,
    brand: "Generic",
    warranty: "1 year",
    delivery: "Free delivery within Kampala",
  },
  {
    id: 4,
    title: "Hikvision Video Intercom Kit",
    description: "Advanced Video intercom kit for secure room or property access.",
    price: 750000,
    originalPrice: 850000,
    category: "access-control",
    image: makeProductImages(8)[0],
    images: makeProductImages(8),
    inStock: true,
    brand: "Hikvision",
    warranty: "1 year",
    delivery: "Free delivery within Kampala",
  },
  {
    id: 5,
    title: "Access Control System kit",
    description: "High grade secure access control system kit campatible with fingerprint, RFID Cards and Password.",
    price: 250000,
    category: "access-control",
    image: makeProductImages(9)[0],
    images: makeProductImages(9),
    inStock: true,
    brand: "Zteco",
    warranty: "1 year",
    delivery: "Free delivery within Kampala",
  },
  {
    id: 15,
    title: "D5 SMART Gate Motor",
    description: "Remote controlled D5 Smart gate motor for automated gates.",
    price: 280000,
    category: "automatic-gates",
    image: makeProductImages(10)[0],
    images: makeProductImages(10),
    inStock: true,
    brand: "Secura",
    warranty: "1 year",
    delivery: "Free delivery within Kampala",
  },
  {
    id: 18,
    title: "CAT 6 Indoor Network Cable",
    description: "Fast CAT 6 network cable for indoor network device connectivity.",
    price: 1800000,
    category: "access-control",
    image: makeProductImages(11)[0],
    images: makeProductImages(11),
    inStock: true,
    brand: "ZKTeco",
    warranty: "2 years",
    delivery: "Free delivery within Kampala",
  },
  {
    id: 26,
    title: "CARRETT Metal Detector",
    description: "Highly sensitive metal detactor with beep sound and alarm.",
    price: 180000,
    category: "access-control",
    image: makeProductImages(12)[0],
    images: makeProductImages(12),
    inStock: true,
    brand: "CARRETT",
    warranty: "1 year",
    delivery: "Free delivery within Kampala",
  },
  {
    id: 6,
    title: "Burlar Alarm Kit",
    description: "High grade buglar alarms kit with motion detector and control device.",
    price: 2100000,
    originalPrice: 2500000,
    category: "access-control",
    image: makeProductImages(13)[0],
    images: makeProductImages(13),
    inStock: true,
    brand: "Nice",
    warranty: "3 years",
    delivery: "Free delivery within Kampala",
  },
  {
    id: 7,
    title: "Swing Gate Opener Kit",
    description: "Dual swing gate motor kit with obstacle detection and soft start/stop.",
    price: 1800000,
    category: "automatic-gates",
    image: makeProductImages(14)[0],
    images: makeProductImages(14),
    inStock: false,
    brand: "FAAC",
    warranty: "2 years",
    delivery: "Free delivery within Kampala",
  },
  {
    id: 16,
    title: "HIKVISION Bullet Camera",
    description: "High definition hikvision bullet camera for outdoor survillence.",
    price: 45000,
    category: "cctv",
    image: makeProductImages(15)[0],
    images: makeProductImages(15),
    inStock: true,
    brand: "HIKVISION",
    warranty: "1 year",
    delivery: "Free delivery within Kampala",
  },
  {
    id: 22,
    title: "CARRETT Metal Detector",
    description: "Highly sensitive metal detactor with beep sound and alarm.",
    price: 350000,
    category: "access-control",
    image: makeProductImages(16)[0],
    images: makeProductImages(16),
    inStock: true,
    brand: "CARRETT",
    warranty: "2 years",
    delivery: "Free delivery within Kampala",
  },
  {
    id: 28,
    title: "6 PoE Switch",
    description: "Power over Ethernet Switch with 6 ports.",
    price: 3200000,
    category: "networks",
    image: makeProductImages(17)[0],
    images: makeProductImages(17),
    inStock: true,
    brand: "Universal",
    warranty: "2 years",
    delivery: "Free delivery within Kampala",
  },
  {
    id: 8,
    title: "HIKVISION Dome Camera",
    description: "High definition hikvison dome camera with voice recording.",
    price: 550000,
    originalPrice: 650000,
    category: "cctv",
    image: makeProductImages(18)[0],
    images: makeProductImages(18),
    inStock: true,
    brand: "Nemtek",
    warranty: "2 years",
    delivery: "Free delivery within Kampala",
  },
  {
    id: 9,
    title: "Hisense AC",
    description: "High grade hisense AC with cooling control remote",
    price: 180000,
    category: "cooling-systems",
    image: makeProductImages(19)[0],
    images: makeProductImages(19),
    inStock: true,
    brand: "Security Plus",
    warranty: "1 year",
    delivery: "Free delivery within Kampala",
  },
  {
    id: 19,
    title: "WIFI Smart Camera",
    description: "Complete solar-powered wifi enabled smart camera kit with high definition camera and solar panels.",
    price: 950000,
    originalPrice: 1100000,
    category: "cctv",
    image: makeProductImages(20)[0],
    images: makeProductImages(20),
    inStock: true,
    brand: "Nemtek",
    warranty: "2 years",
    delivery: "Free delivery within Kampala",
  },
  /*{
    id: 25,
    title: "Fence Warning Sign Kit",
    description: "Pack of 10 electric fence warning signs with UV protection.",
    price: 35000,
    category: "electric-fence",
    image: makeProductImages(21)[0],
    images: makeProductImages(21),
    inStock: true,
    brand: "Generic",
    warranty: "1 year",
    delivery: "Free delivery within Kampala",
  },
  {
    id: 10,
    title: "Wireless Alarm Kit",
    description: "Smart alarm system with door sensors, motion detectors, and mobile app.",
    price: 450000,
    originalPrice: 550000,
    category: "alarms",
    image: makeProductImages(22)[0],
    images: makeProductImages(22),
    inStock: true,
    brand: "Paradox",
    warranty: "2 years",
    delivery: "Free delivery within Kampala",
  },
  {
    id: 11,
    title: "Smoke Detector Wireless",
    description: "Wireless smoke sensor with 85dB siren and low battery indicator.",
    price: 95000,
    category: "alarms",
    image: makeProductImages(23)[0],
    images: makeProductImages(23),
    inStock: true,
    brand: "Honeywell",
    warranty: "1 year",
    delivery: "Free delivery within Kampala",
  },
  {
    id: 20,
    title: "GSM Alarm Communicator",
    description: "Add GSM calling to any alarm panel with voice and SMS alerts.",
    price: 320000,
    category: "alarms",
    image: makeProductImages(24)[0],
    images: makeProductImages(24),
    inStock: true,
    brand: "Paradox",
    warranty: "2 years",
    delivery: "Free delivery within Kampala",
  },
  {
    id: 27,
    title: "PIR Motion Sensor",
    description: "Wireless PIR detector with pet immunity and 12m range.",
    price: 85000,
    category: "alarms",
    image: makeProductImages(25)[0],
    images: makeProductImages(25),
    inStock: true,
    brand: "Honeywell",
    warranty: "1 year",
    delivery: "Free delivery within Kampala",
  },
  {
    id: 12,
    title: "Video Intercom 7\"",
    description: "Indoor monitor with touchscreen, WiFi, and remote unlock feature.",
    price: 650000,
    originalPrice: 750000,
    category: "intercom",
    image: makeProductImages(26)[0],
    images: makeProductImages(26),
    inStock: true,
    brand: "Bticino",
    warranty: "2 years",
    delivery: "Free delivery within Kampala",
  },
  {
    id: 13,
    title: "Outdoor Intercom Station",
    description: "Weatherproof door station with camera, keypad, and card reader.",
    price: 450000,
    category: "intercom",
    image: makeProductImages(27)[0],
    images: makeProductImages(27),
    inStock: true,
    brand: "2N",
    warranty: "2 years",
    delivery: "Free delivery within Kampala",
  },
  {
    id: 23,
    title: "Wireless Doorbell Camera",
    description: "Smart doorbell with HD camera, two-way audio, and motion alerts.",
    price: 280000,
    originalPrice: 350000,
    category: "intercom",
    image: makeProductImages(28)[0],
    images: makeProductImages(28),
    inStock: true,
    brand: "Ring",
    warranty: "1 year",
    delivery: "Free delivery within Kampala",
  }*/
];

export function getProductById(id: number): Product | undefined {
  return products.find((product) => product.id === id);
}

export function getRecommendedProducts(currentProduct: Product, limit = 8): Product[] {
  return products.filter((product) => product.category === currentProduct.category && product.id !== currentProduct.id).slice(0, limit);
}

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("en-UG", {
    style: "currency",
    currency: "UGX",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(price);
}
